import re
from random import randint
nyms = [['ade', 'aid', 'aide'],
        ['aisle', "I'll", 'isle'],
        ['ait', 'ate', 'eight'],
        ['aye', 'eye', 'I'],
        ['axel', 'axil', 'axle'],
        ['bald', 'balled', 'bawled'],
        ['bases', 'basis', 'basses'],
        ['beau', 'bo', 'bow'],
        ['bight', 'bite', 'byte'],
        ['boar', 'boor', 'bore'],
        ['bold', 'bolled', 'bowled'],
        ['bole', 'boll', 'bowl'],
        ['born', 'borne', 'bourne'],
        ['borough', 'burro', 'burrow'],
        ['braise', 'brays', 'braze'],
        ['birr', 'bur', 'burr'],
        ['call', 'caul', 'col'],
        ['cedar', 'ceder', 'seeder'],
        ['ceiling', 'sealing', 'seeling'],
        ['censer', 'censor', 'sensor'],
        ['cent', 'scent', 'sent'],
        ['Chile', 'chili', 'chilly'],
        ['chord', 'cord', 'cored'],
        ['coal', 'cole', 'kohl'],
        ['coarse', 'corse', 'course'],
        ['coign', 'coin', 'quoin'],
        ['coward', 'cowered', 'cowherd'],
        ['does', 'doughs', 'doze'],
        ['earn', 'erne', 'urn'],
        ['eaves', 'eves', 'Yves'],
        ['ewes', 'use', 'yews'],
        ['fain', 'fane', 'feign'],
        ['faro', 'farrow', 'pharoah'],
        ['firs', 'furs', 'furze'],
        ['flew', 'flu', 'flue'],
        ['for', 'fore', 'four'],
        ['frees', 'freeze', 'frieze'],
        ['gild', 'gilled', 'guild'],
        ['heal', 'heel', "he'll"],
        ['hi', 'hie', 'high'],
        ['holey', 'holy', 'wholly'],
        ['idle', 'idol', 'idyll'],
        ['knead', 'kneed', 'need'],
        ['knot', 'naught', 'not'],
        ['knows', 'noes', 'nose'],
        ['Lapps', 'laps', 'lapse'],
        ['lays', 'laze', 'leis'],
        ['liar', 'lier', 'lyre'],
        ['load', 'lode', 'lowed'],
        ['mead', 'Mede', 'meed'],
        ['meat', 'meet', 'mete'],
        ['mold', 'moled', 'mould'],
        ['mhorr', 'moor', 'more'],
        ['nay', 'nee', 'neigh'],
        ['pair', 'pare', 'pear'],
        ['palate', 'palette', 'pallet'],
        ['plainer', 'planar', 'planer'],
        ['polar', 'poler', 'poller'],
        ['poor', 'pore', 'pour'],
        ['psis', 'sighs', 'size'],
        ['rain', 'reign', 'rein'],
        ['raiser', 'razer', 'razor'],
        ['rapped', 'rapt', 'wrapped'],
        ['read', 'rede', 'reed'],
        ['road', 'rode', 'rowed'],
        ['rood', 'rude', 'rued'],
        ['rheumy', 'roomie', 'roomy'],
        ['roos', 'rues', 'ruse'],
        ['sacs', 'sacks', 'sax'],
        ['shier', 'shire', 'shyer'],
        ['sic', 'sick', 'Sikh'],
        ['sics', 'Sikhs', 'six;'],
        ['sign', 'sine', 'syne'],
        ['Sioux', 'sou', 'sue'],
        ['Sol', 'sole', 'soul'],
        ['sold', 'soled', 'souled'],
        ['taught', 'taut', 'tot'],
        ['their', 'there', "they're"],
        ['to', 'too', 'two'],
        ['toad', 'toed', 'towed'],
        ['ton', 'tonne', 'tun'],
        ['vail', 'vale', 'veil'],
        ['vain', 'vane', 'vein'],
        ['vial', 'vile', 'viol'],
        ['wail', 'wale', 'whale'],
        ['ware', 'wear', 'where'],
        ['way', 'weigh', 'whey'],
        ['weal', "we'll", 'wheel'],
        ['weather', 'wether', 'whether'],
        ['whined', 'wind', 'wined'],
        ['adds', 'ads', 'adz', 'adze'],
        ['bi', 'buy', 'by', 'bye'],
        ['carat', 'caret', 'carrot', 'karat'],
        ['cees', 'seas', 'sees', 'seize'],
        ['cense', 'cents', 'scents', 'sense'],
        ['cere', 'sear', 'seer', 'sere'],
        ['cinque', 'sink', 'sync', 'synch'],
        ['cite', 'cyte', 'sight', 'site'],
        ['crews', 'cruise', 'crus', 'cruse'],
        ['dew', 'do', 'doux', 'due'],
        ['eau', 'o', 'oh', 'owe'],
        ['ewe', 'yew', 'you', 'U'],
        ['gnu', 'knew', 'new', 'nu'],
        ['heigh', 'hi', 'hie', 'high'],
        ['hoard', 'horde', 'hoared', 'whored'],
        ['mall', 'moll', 'maul', 'mawl'],
        ['medal', 'meddle', 'metal', 'mettle'],
        ['oar', "o'er", 'or', 'ore'],
        ['pairish', 'parish', 'pearish', 'perish'],
        ['peak', 'peek', 'peke', 'pique'],
        ['praise', 'prase', 'prays', 'preys'],
        ['rhos', 'roes', 'rose', 'rows'],
        ['right', 'rite', 'wright', 'write'],
        ['teas', 'tease', 'tees', 'tis'],
        ['wade', 'wayed', 'weighed', 'wheyed'],
        ['weald', 'wealed', 'wheeled', 'wield'],
        ['seau', 'sew', 'so', 'soe', 'sow'],
        ['air', 'are', "e'er", 'ere', 'err', 'heir'],
        ['raise', 'rays', 'rase', 'raze', 'rehs', 'réis', 'res']]
        
userinput = input("Sentence: ")
print()
userinput = re.sub(r"\r\n", " ", userinput)
userinput2 = re.findall(r"[\w']+|[.,!?;' ]", userinput)

indx = 0
for word in userinput2:
  try:
    val = [val for val in nyms if word in val][0]
    val1 = nyms.index(val)
    val2 = val.index(word)
    print('The index is (%d,%d)'%(val1,val2))
    userinput2[indx] = nyms[val1][randint(0, len(val)-1)]
    print(userinput2[indx])
  except:
    pass
  indx += 1
print(userinput2)

for indx in range(len(userinput2)):
  print(userinput2[indx], end='')
print()
